functionfs.gadget: Call function.start before creating its symlink.
Otherwise, the function may reject changing its configuration, for example
SourceSink (usb_f_ss_lb) as of 5.10.46 fails with:
  IOError: [Errno 16] Device or resource busy